services:
  # Основной сервис обработки
  yolo-app:
    build: .
    container_name: yolo-app
    ports:
      - "5000:5000"  # FastAPI
      - "8000:8000"  # Prometheus метрики
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./configs:/app/configs
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Явное указание GPU
    networks:
      - yolo-net

  # База данных для результатов
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: yolo_results
      POSTGRES_USER: yolo
      POSTGRES_PASSWORD: yolo123
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - yolo-net

  # Мониторинг
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres
    networks:
      - yolo-net

volumes:
  pg_data:
  grafana_data:

networks:
  yolo-net:
    driver: bridge